export const projectStats = { experiences: 20, schools: 19 };
export const categories = ['Círculos de la palabra', 'Jueces de paz', 'Teatro y sociodrama', 'Semilleros de investigación', 'Clínicas de las emociones', 'Museos de la memoria'];
export const experiences = categories.map((category, index) => ({ id: index + 1, category, name: ['La palabra nos une', 'Voces que median', 'En la piel del otro', 'Semillas de paz', 'Sentir para convivir', 'Memorias que abrazan'][index], description: ['El diálogo como punto de encuentro para escucharnos y construir acuerdos.', 'El protagonismo estudiantil en la mediación y la resolución de conflictos.', 'El teatro como espacio para reconocer al otro y transformar los conflictos.', 'Preguntas e investigación para comprender la convivencia escolar.', 'El cuidado y el reconocimiento de las emociones en la vida escolar.', 'La memoria de la escuela como camino hacia la reconciliación.'][index] }));
export const bookChapters = [
 { title: 'De las aulas para el mundo', label: 'Presentación', paragraphs: ['La paz escolar se construye en lo cotidiano: en una conversación, en la escucha y en los acuerdos que hacemos para convivir.', 'Este libro virtual reúne la propuesta de sistematización de 20 experiencias de 19 colegios públicos y privados. Una memoria colectiva para reconocer los saberes de quienes construyen paz desde las aulas.'], items: ['Experiencias y metodologías', 'Voces de estudiantes y docentes', 'Memoria de los encuentros'] },
 { title: 'Muchas formas de construir paz', label: '01 · Metodologías', paragraphs: ['Cada escuela encuentra sus propios caminos para transformar los conflictos. El catálogo organiza las experiencias por sus metodologías pedagógicas.'], items: categories },
 { title: 'La historia de cada experiencia', label: '02 · Sistematización', paragraphs: ['La unidad de registro es la experiencia, no el colegio. Cada ficha permite reconocer su trayectoria, sus protagonistas y su aporte a la convivencia.'], items: ['Institución y nombre de la experiencia', 'Categoría y metodología', 'Origen: cuándo y por qué nace', 'Actores líderes y área curricular', 'Rol del estudiante y sustentabilidad', 'Impacto e indicadores de gestión'] },
 { title: 'El estudiante como protagonista', label: '03 · Participación', paragraphs: ['El registro de cada experiencia reconoce la participación de estudiantes, docentes y directivos, así como los grados y áreas curriculares involucrados.', 'La sustentabilidad del proceso contempla la capacidad de los estudiantes para gestionar espacios de diálogo y resolver problemas con autonomía.'], items: ['Liderazgo estudiantil', 'Mediación y mesas de diálogo', 'Continuidad del proceso'] },
 { title: 'Memorias que siguen creciendo', label: '04 · Archivo', paragraphs: ['Los encuentros de 2025 y 2026 tienen un lugar en este archivo: fotografías, piezas gráficas, entrevistas y registros de las experiencias.', 'Los contenidos de esta edición de muestra provienen de la propuesta compartida. El libro compilatorio, sus capítulos y los registros de las instituciones están pendientes de incorporar.'], items: ['Encuentro 2025 · Registro por incorporar', 'II Encuentro 2026 · Afiche disponible', 'Libro compilatorio · Documento pendiente'] },
];
