import { createFileRoute } from '@tanstack/react-router';
import { useState } from 'react';
import { ChevronLeft, ChevronRight, Download, BookOpen } from 'lucide-react';
import { PeaceLayout, PageHeading, peaceHead } from '@/components/peace-layout';
import { bear } from '@/components/peace-content';
import { Button } from '@/components/ui/button';
import { bookChapters } from '@/lib/peace-data';
export const Route=createFileRoute('/libro')({head:()=>peaceHead('Memorias de paz · Libro virtual','Libro virtual de muestra con las metodologías y la propuesta de sistematización de experiencias de paz escolar.'),component:Libro});
function Libro(){const [page,setPage]=useState(0);const chapter=bookChapters[page];if(!chapter)return null;return <PeaceLayout><PageHeading label="Un libro, muchas voces" title="Memorias de paz." description="De las aulas para el mundo. Un recorrido por la propuesta de sistematización y la memoria de nuestra comunidad."/><section className="wrap reader"><div className="reader-controls"><span className="text-sm text-muted-foreground flex items-center gap-2"><BookOpen size={16}/> Edición de muestra · 2025—2026</span><Button variant="outline" disabled title="El PDF compilatorio aún no ha sido suministrado"><Download/> PDF pendiente</Button></div><div className="reader-book"><div className="reader-left"><div><div className="eyebrow text-primary-foreground">GESTORES DE PAZ ESCOLARES</div><h2>Memorias<br/>de paz.</h2><p>De las aulas para el mundo</p></div><img src={bear} alt="Osito gestor de paz" width="110" height="130"/><small>BOGOTÁ · 2025—2026 · IPAZUD</small></div><div className="reader-page" aria-live="polite"><div className="eyebrow">{chapter.label}</div><h3>{chapter.title}</h3>{chapter.paragraphs.map(p=><p key={p}>{p}</p>)}<ul>{chapter.items.map(item=><li key={item}>{item}</li>)}</ul><div className="page-number">{String(page+1).padStart(2,'0')} / {String(bookChapters.length).padStart(2,'0')}</div></div></div><div className="reader-navigation"><Button variant="outline" size="icon" aria-label="Página anterior" disabled={page===0} onClick={()=>setPage(p=>p-1)}><ChevronLeft/></Button><span className="text-sm text-muted-foreground">{page+1} de {bookChapters.length}</span><Button variant="outline" size="icon" aria-label="Página siguiente" disabled={page===bookChapters.length-1} onClick={()=>setPage(p=>p+1)}><ChevronRight/></Button></div><p className="notice">Esta es una edición de muestra con la información compartida. El libro compilatorio en PDF y sus capítulos se incorporarán cuando estén disponibles.</p></section></PeaceLayout>}
