import { Link, useLocation } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowUpRight, Menu, X, HeartHandshake } from 'lucide-react';
import { Button } from '@/components/ui/button';
import bear from '@/assets/peace-bear.png';
export const navItems = [{ to: '/', label: 'Inicio' }, { to: '/encuentros', label: 'Encuentros' }, { to: '/experiencias', label: 'Experiencias' }, { to: '/libro', label: 'Libro virtual' }, { to: '/galeria', label: 'Galería' }] as const;
export function Brand() { return <Link to="/" className="brand"><img src={bear} alt="Osito gestor de paz" width="54" height="60"/><div><strong>Gestores de Paz<br/>Escolares</strong><small>BOGOTÁ · COLOMBIA</small></div></Link> }
export function PeaceLayout({ children }: { children: React.ReactNode }) {
 const [open, setOpen] = useState(false); const { pathname } = useLocation();
 return <><div className="institution-bar"><div className="wrap"><a href="https://ipazud.udistrital.edu.co/" target="_blank" rel="noreferrer">Universidad Distrital Francisco José de Caldas <span className="institution-extra"> · IPAZUD</span></a><span>De las aulas para el mundo… sembrando paz</span></div></div><header className="nav wrap"><Brand/><nav aria-label="Navegación principal" className={`nav-links ${open ? 'open' : ''}`}>{navItems.map(item=><Link key={item.to} to={item.to} className={`nav-link ${pathname===item.to ? 'active' : ''}`} onClick={()=>setOpen(false)}>{item.label}</Link>)}<Button size="sm" asChild><Link to="/red">Nuestra red <ArrowUpRight/></Link></Button></nav><Button variant="ghost" size="icon" className="menu-button" aria-label={open?'Cerrar menú':'Abrir menú'} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></header><main>{children}</main><section className="community-band"><div className="wrap"><div><h2>La paz crece cuando la construimos juntos.</h2><p>Una red de estudiantes, docentes y colegios que transforma su entorno.</p></div><Button asChild><Link to="/red"><HeartHandshake/> Conoce nuestra red <ArrowUpRight/></Link></Button></div></section><footer className="footer"><div className="wrap"><div className="footer-top"><Brand/><div className="footer-partners">Una iniciativa de<br/><strong>Universidad Distrital Francisco José de Caldas · IPAZUD</strong><br/>Corporación Escenarios para la Paz (E-PAZ)</div></div><div className="footer-bottom"><span>© 2026 Gestores de Paz Escolares · Bogotá, Colombia</span><span>Propuesta visual · Fotografías ilustrativas y fichas de muestra</span><a href="https://ipazud.udistrital.edu.co/" target="_blank" rel="noreferrer">Sitio institucional ↗</a></div></div></footer></>
}
export function PageHeading({ label, title, description }: {label:string;title:string;description:string}) {return <section className="page-heading"><div className="wrap"><div className="eyebrow">{label}</div><h1>{title}</h1><p>{description}</p></div></section>}
export function peaceHead(title:string,description:string){return {meta:[{title:`${title} | Gestores de Paz Escolares`},{name:'description',content:description},{property:'og:title',content:`${title} | Gestores de Paz Escolares`},{property:'og:description',content:description},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}}
