import { Link } from '@tanstack/react-router';
import { ArrowRight, ArrowUpRight, CalendarDays, MapPin, Archive, BookOpen, Building2, Users, HeartHandshake } from 'lucide-react';
import { Button } from '@/components/ui/button';
import bear from '@/assets/peace-bear.png';
import photo from '@/assets/peace-circle.jpg';
import workshop from '@/assets/peace-workshop.jpg';
import mural from '@/assets/peace-mural.jpg';
import poster from '@/assets/encuentro-2026.png';
import { projectStats, type experiences } from '@/lib/peace-data';
export function Stats(){return <section className="stats"><div className="wrap stats-inner">{[{icon:BookOpen,value:projectStats.experiences,label:'Experiencias de paz'},{icon:Building2,value:projectStats.schools,label:'Colegios participantes'},{icon:Users,value:'2',label:'Años de encuentro'},{icon:HeartHandshake,value:'Una',label:'Comunidad que transforma'}].map(({icon:Icon,value,label})=><div className="stat" key={label}><div className="stat-icon"><Icon size={19}/></div><div><strong>{value}</strong><small>{label}</small></div></div>)}</div></section>}
export function EventCards({year='all'}:{year?:string}){return <div className="event-grid">{year!=='2025'&&<article className="event-card"><div className="event-picture"><img src={photo} alt="Estudiantes compartiendo un círculo de diálogo; fotografía ilustrativa" width="1536" height="1024" loading="lazy"/><span className="year">2026</span></div><div className="event-copy"><span className="badge">II encuentro · 2026</span><h3>Encuentro de Gestores<br/>de Paz Escolares</h3><div className="event-meta"><CalendarDays size={13}/>1 y 2 de septiembre de 2026</div><div className="event-meta"><MapPin size={13}/>Universidad Distrital · Bogotá</div><Button variant="link" className="event-link" asChild><a href="https://ipazud.udistrital.edu.co/noticia/ii-encuentro-de-gestores-de-paz-escolares" target="_blank" rel="noreferrer">Ver el encuentro <ArrowUpRight/></a></Button></div></article>}{year!=='2026'&&<article className="archive-card"><Archive className="archive-icon"/><div className="eyebrow">Nuestra memoria · 2025</div><h3>Los primeros pasos de un camino compartido.</h3><p>Un espacio para conservar las voces y experiencias del encuentro anterior.</p><Button variant="link" className="justify-start px-0" asChild><Link to="/galeria">Explorar el archivo <ArrowRight/></Link></Button><small className="text-muted-foreground text-[10px] mt-2">Registros de 2025 pendientes de incorporar</small></article>}</div>}
export function BookCover(){return <div className="book-object" aria-label="Portada del libro Memorias de paz"><div className="book-cover"><div><small>GESTORES DE PAZ ESCOLARES</small><h3>Memorias<br/>de paz.</h3><p>De las aulas para el mundo</p></div><img src={bear} alt="Osito del encuentro" loading="lazy" width="90" height="90"/><div className="book-cover-bottom"><span>BOGOTÁ · 2025—2026</span><span>IPAZUD</span></div></div></div>}
export function ExperienceCard({experience,onOpen}:{experience:(typeof experiences)[number];onOpen:()=>void}) {return <article className="experience-card"><div className="experience-image"><img src={[photo,workshop,mural][(experience.id-1)%3]} alt="Comunidad escolar; imagen ilustrativa" width="1024" height="768" loading="lazy"/><span className="badge">{experience.category}</span></div><div className="experience-body"><h3>{experience.name}</h3><p>{experience.description}</p><div className="experience-bottom"><span>Ficha ilustrativa · Bogotá</span><Button variant="ghost" size="icon" aria-label={`Ver ficha de ${experience.name}`} onClick={onOpen}><ArrowUpRight/></Button></div></div></article>}
export { poster, photo, bear };
