/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EncuentrosRouteImport } from './routes/encuentros'
import { Route as ExperienciasRouteImport } from './routes/experiencias'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as LibroRouteImport } from './routes/libro'
import { Route as RedRouteImport } from './routes/red'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EncuentrosRoute = EncuentrosRouteImport.update({
  id: '/encuentros',
  path: '/encuentros',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasRoute = ExperienciasRouteImport.update({
  id: '/experiencias',
  path: '/experiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const LibroRoute = LibroRouteImport.update({
  id: '/libro',
  path: '/libro',
  getParentRoute: () => rootRouteImport,
} as any)
const RedRoute = RedRouteImport.update({
  id: '/red',
  path: '/red',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/encuentros': typeof EncuentrosRoute
  '/experiencias': typeof ExperienciasRoute
  '/galeria': typeof GaleriaRoute
  '/libro': typeof LibroRoute
  '/red': typeof RedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/encuentros': typeof EncuentrosRoute
  '/experiencias': typeof ExperienciasRoute
  '/galeria': typeof GaleriaRoute
  '/libro': typeof LibroRoute
  '/red': typeof RedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/encuentros': typeof EncuentrosRoute
  '/experiencias': typeof ExperienciasRoute
  '/galeria': typeof GaleriaRoute
  '/libro': typeof LibroRoute
  '/red': typeof RedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/encuentros' | '/experiencias' | '/galeria' | '/libro' | '/red'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/encuentros' | '/experiencias' | '/galeria' | '/libro' | '/red'
  id:
    | '__root__'
    | '/'
    | '/encuentros'
    | '/experiencias'
    | '/galeria'
    | '/libro'
    | '/red'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EncuentrosRoute: typeof EncuentrosRoute
  ExperienciasRoute: typeof ExperienciasRoute
  GaleriaRoute: typeof GaleriaRoute
  LibroRoute: typeof LibroRoute
  RedRoute: typeof RedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encuentros': {
      id: '/encuentros'
      path: '/encuentros'
      fullPath: '/encuentros'
      preLoaderRoute: typeof EncuentrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias': {
      id: '/experiencias'
      path: '/experiencias'
      fullPath: '/experiencias'
      preLoaderRoute: typeof ExperienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libro': {
      id: '/libro'
      path: '/libro'
      fullPath: '/libro'
      preLoaderRoute: typeof LibroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/red': {
      id: '/red'
      path: '/red'
      fullPath: '/red'
      preLoaderRoute: typeof RedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EncuentrosRoute: EncuentrosRoute,
  ExperienciasRoute: ExperienciasRoute,
  GaleriaRoute: GaleriaRoute,
  LibroRoute: LibroRoute,
  RedRoute: RedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
